#!/usr/bin/env python3

import sys
import os.path
import base64


def decode_b64(encoded_string):
    decodedBytes = base64.b64decode(encoded_string)

    return str(decodedBytes, "utf-8")


def read_file_content(filename):
    content = ""

    with open(filename, "r") as fh:
        lines = fh.readlines()
        for line in lines:
            content += line

    return content


def write_contents_to_file(filename, content):
    if not os.path.isfile(filename):
        raise FileNotFoundError("File not found!")

    output_filename = str.join("_decoded", os.path.splitext(filename))
    if os.path.isfile(output_filename):
        raise FileExistsError("File already exists!")

    with open(output_filename, "w") as fh:
        fh.write(content)

    return True


if __name__ == "__main__":
    for index, filename in enumerate(sys.argv[1:]):
        print("Decoding {}".format(filename))
        try:
            encoded_b64 = read_file_content(filename)
            decoded_data = decode_b64(encoded_b64)
            write_contents_to_file(filename, decoded_data)
            print("Success")

        except Exception as e:
            print("Processing Error: {0}".format(e))
